language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
before_install:
- ./qshell account $AK $SK
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- ./qshell qupload config
